export interface GithubUser {
  login: string,
  id: number,
  node_id: string,
  avatar_url: string,
  gravatar_id: string,
  url: string,
  html_url: string,
  followers_url: string,
  following_url: string,
  gists_url: string,
  starred_url: string,
  subscriptions_url: string,
  organizations_url: string,
  repos_url: string,
  events_url: string,
  received_events_url: string,
  type: string,
  site_admin: boolean,
  name: string,
  company: any,
  blog: string,
  location: string,
  email: any,
  hireable: boolean,
  bio: string,
  twitter_username: string,
  public_repos: number,
  public_gists: number,
  followers: number,
  following: number,
  created_at: string,
  updated_at: string
}

/*
*
*  "login": "kevindaviladev",
      "id": 56242609,
      "node_id": "MDQ6VXNlcjU2MjQyNjA5",
      "avatar_url": "https://avatars.githubusercontent.com/u/56242609?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevindaviladev",
      "html_url": "https://github.com/kevindaviladev",
      "followers_url": "https://api.github.com/users/kevindaviladev/followers",
      "following_url": "https://api.github.com/users/kevindaviladev/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevindaviladev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevindaviladev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevindaviladev/subscriptions",
      "organizations_url": "https://api.github.com/users/kevindaviladev/orgs",
      "repos_url": "https://api.github.com/users/kevindaviladev/repos",
      "events_url": "https://api.github.com/users/kevindaviladev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevindaviladev/received_events",
      "type": "User",
      "site_admin": false,
      "name": "Kevin Davila Benavides",
      "company": null,
      "blog": "",
      "location": "Perú",
      "email": null,
      "hireable": true,
      "bio": "Google Developer Expert (GDE) - Angular.\r\nFrontend Developer\r\nAmante de Angular, Postgresql y las ranas.",
      "twitter_username": "kevindaviladev",
      "public_repos": 54,
      "public_gists": 0,
      "followers": 85,
      "following": 3,
      "created_at": "2019-10-07T03:17:31Z",
      "updated_at": "2023-11-16T03:20:26Z"
* */
